---
trigger:
  branches:
    include:
      - production-hs
  paths:
    include:
      - /10_projects/07_CenAudit
      - /20_pipelines/HighSecure/10_Paas/54_cenadt
      - /env/10_Paas/54_cenadt
# pr:
#   branches:
#     include:
#       - production-hs
#   paths:
#     include:
#       - /10_projects/07_CenAudit
#       - /20_pipelines/HighSecure/10_Paas/54_cenadt
#       - /env/10_Paas/54_cenadt

# pool:
#   name: "Ubuntu-Agents"

variables:
  - template: 01_cenadt-Deployment.yml
  - template: 02_cenadt-paas-vars-production.yml
  - template: /20_pipelines/HighSecure/github-branch.yml

# Anything below should not be modified ##
stages:
# Production Cenadt
  - template: ../../../Common/azure-deployment.yml
    parameters:
      environment_name: "Productioncenadt"
      branch_name: ${{ variables.branch_name }}
      tf_workingfolder: ${{ variables.tfWorkingFolder_cenadtapp }}
      stage_name: "Production_cenadtapp"
      deployment_jobname: "Deployment_Production_cenadtApp"
      teardown_jobname: "Teardown_Production_cenadtApp"
      teardown_environment: ${{ variables.teardownEnvironment_production_cenadtapp }}
      service_connectionname: ${{ variables.serviceConnectionName_production_cenadtapp }}
      tf_stateresourcegroupname: ${{ variables.tfStateResourceGroupName_production_cenadtapp }}
      tf_statestorageaccountname: ${{ variables.tfStateStorageAccountName_production_cenadtapp }}
      tf_statecontainername: ${{ variables.tfStateContainerName_production_cenadtapp }}
      tf_statefile: ${{ variables.tfStateFile_production_cenadtapp }}
      env_configuration: ${{ variables.envConfiguration_production_cenadtapp }}
      enable_stage: ${{ variables.enable_production_cenadtapp }}
      agent_pool: ${{ variables.agent_pool_production_cenadtapp }}
      enable_apply: ${{ variables.enable_apply_production_cenadtapp }}
