---
trigger:
  branches:
    include:
      - production-hs
  paths:
    include:
      - /10_projects/08_ComsyHS/01_Networking
      - /10_projects/11_ApexHS/01_Networking
      - /20_pipelines/HighSecure/01_Networking/53_mngd
      - /env/01_Networking/53_mngd
# pr:
#   branches:
#     include:
#       - production-hs
#   paths:
#     include:
#       - /10_projects/08_ComsyHS/01_Networking
#       - /10_projects/11_ApexHS/01_Networking
#       - /20_pipelines/HighSecure/01_Networking/53_mngd
#       - /env/01_Networking/53_mngd

# pool:
#   name: "Ubuntu-Agents"

variables:
  - template: 01_mngd-Deployment.yml
  - template: 02_mngd-networking-vars-production.yml
  - template: 03_mngd-networking-vars-test.yml
  - template: /20_pipelines/HighSecure/github-branch.yml

# Anything below should not be modified ##
stages:
  # mngdapp test & mngdApex Tst
  - template: ../../../Common/azure-deployment.yml
    parameters:
      environment_name: "Testmngdapp"
      branch_name: ${{ variables.branch_name }}
      tf_workingfolder: ${{ variables.tfWorkingFolder_mngdapp }}
      stage_name: "Test_mngdapp"
      deployment_jobname: "Deployment_Test_mngdapp"
      teardown_jobname: "Teardown_Test_mngdapp"
      teardown_environment: ${{ variables.teardownEnvironment_test_mngdapp }}
      service_connectionname: ${{ variables.serviceConnectionName_test_mngdapp }}
      tf_stateresourcegroupname: ${{ variables.tfStateResourceGroupName_test_mngdapp }}
      tf_statestorageaccountname: ${{ variables.tfStateStorageAccountName_test_mngdapp }}
      tf_statecontainername: ${{ variables.tfStateContainerName_test_mngdapp }}
      tf_statefile: ${{ variables.tfStateFile_test_mngdapp }}
      env_configuration: ${{ variables.envConfiguration_test_mngdapp }}
      enable_stage: ${{ variables.enable_test_mngdapp }}
      agent_pool: ${{ variables.agent_pool_test_mngdapp }}
      enable_apply: ${{ variables.enable_apply_test_mngdapp }}
  # mngdapex Dev
  - template: ../../../Common/azure-deployment.yml
    parameters:
      environment_name: "Testmngdapex"
      branch_name: ${{ variables.branch_name }}
      tf_workingfolder: ${{ variables.tfWorkingFolder_mngdapex }}
      stage_name: "Test_mngdapex"
      deployment_jobname: "Deployment_Test_mngdapex"
      teardown_jobname: "Teardown_Test_mngdapex"
      teardown_environment: ${{ variables.teardownEnvironment_test_mngdapex }}
      service_connectionname: ${{ variables.serviceConnectionName_test_mngdapex }}
      tf_stateresourcegroupname: ${{ variables.tfStateResourceGroupName_test_mngdapex }}
      tf_statestorageaccountname: ${{ variables.tfStateStorageAccountName_test_mngdapex }}
      tf_statecontainername: ${{ variables.tfStateContainerName_test_mngdapex }}
      tf_statefile: ${{ variables.tfStateFile_test_mngdapex }}
      env_configuration: ${{ variables.envConfiguration_test_mngdapex }}
      enable_stage: ${{ variables.enable_test_mngdapex }}
      agent_pool: ${{ variables.agent_pool_test_mngdapex }}
      enable_apply: ${{ variables.enable_apply_test_mngdapex }}
  # mngdapex Uat
  - template: ../../../Common/azure-deployment.yml
    parameters:
      environment_name: "Testmngdapex_uat"
      branch_name: ${{ variables.branch_name }}
      tf_workingfolder: ${{ variables.tfWorkingFolder_mngdapex_uat }}
      stage_name: "Test_mngdapex_uat"
      deployment_jobname: "Deployment_Test_mngdapex_uat"
      teardown_jobname: "Teardown_Test_mngdapex_uat"
      teardown_environment: ${{ variables.teardownEnvironment_test_mngdapex_uat }}
      service_connectionname: ${{ variables.serviceConnectionName_test_mngdapex_uat }}
      tf_stateresourcegroupname: ${{ variables.tfStateResourceGroupName_test_mngdapex_uat }}
      tf_statestorageaccountname: ${{ variables.tfStateStorageAccountName_test_mngdapex_uat }}
      tf_statecontainername: ${{ variables.tfStateContainerName_test_mngdapex_uat }}
      tf_statefile: ${{ variables.tfStateFile_test_mngdapex_uat }}
      env_configuration: ${{ variables.envConfiguration_test_mngdapex_uat }}
      enable_stage: ${{ variables.enable_test_mngdapex_uat }}
      agent_pool: ${{ variables.agent_pool_test_mngdapex_uat }}
      enable_apply: ${{ variables.enable_apply_test_mngdapex_uat }}
  # Mngdapp Production
  - template: ../../../Common/azure-deployment.yml
    parameters:
      environment_name: "Productionmngdapp"
      branch_name: ${{ variables.branch_name }}
      tf_workingfolder: ${{ variables.tfWorkingFolder_mngdapp }}
      stage_name: "Production_mngdapp"
      deployment_jobname: "Deployment_Production_mngdapp"
      teardown_jobname: "Teardown_Production_mngdapp"
      teardown_environment: ${{ variables.teardownEnvironment_production_mngdapp }}
      service_connectionname: ${{ variables.serviceConnectionName_production_mngdapp }}
      tf_stateresourcegroupname: ${{ variables.tfStateResourceGroupName_production_mngdapp }}
      tf_statestorageaccountname: ${{ variables.tfStateStorageAccountName_production_mngdapp }}
      tf_statecontainername: ${{ variables.tfStateContainerName_production_mngdapp }}
      tf_statefile: ${{ variables.tfStateFile_production_mngdapp }}
      env_configuration: ${{ variables.envConfiguration_production_mngdapp }}
      enable_stage: ${{ variables.enable_production_mngdapp }}
      agent_pool: ${{ variables.agent_pool_production_mngdapp }}
      enable_apply: ${{ variables.enable_apply_production_mngdapp }}
