---
trigger:
  branches:
    include:
      - production-hs
  paths:
    include:
      - /10_projects/08_ComsyHS/17_Keyvault
      - /10_projects/08_ComsyHS/17_Keyvault_prd
      - /10_projects/06_ManagedHS/17_Keyvault_prd
      - /10_projects/06_ManagedHS/17_Keyvault_nprd
      - /10_projects/16_DataGatewayHS/17_Keyvault
      - /20_pipelines/HighSecure/17_Keyvault/53_mngd
      - /env/17_Keyvault/53_mngd/
# pr:
#   branches:
#     include:
#       - production-hs
#   paths:
#     include:
#       - /10_projects/08_ComsyHS/17_Keyvault
#       - /10_projects/16_DataGatewayHS/17_Keyvault
#       - /20_pipelines/HighSecure/17_Keyvault/53_mngd
#       - /env/17_Keyvault/53_mngd/

variables:
  - template: 01_mngd-Deployment.yml
  - template: 03_mngd-kv-vars-test.yml
  - template: 02_mngd-kv-vars-production.yml
  - template: 02_mngd-kv-vars-nonproduction.yml
  - template: /20_pipelines/HighSecure/github-branch.yml

# Anything below should not be modified ##
stages:
# mngdapp test & mngdApex Tst
  - template: ../../../Common/azure-deployment.yml
    parameters:
      environment_name: "Testmngdapp"
      branch_name: ${{ variables.branch_name }}
      tf_workingfolder: ${{ variables.tfWorkingFolder_test_mngdapp }}
      stage_name: "Test_mngdapp"
      deployment_jobname: "Deployment_Test_mngdapp"
      teardown_jobname: "Teardown_Test_mngdapp"
      teardown_environment: ${{ variables.teardownEnvironment_test_mngdapp }}
      service_connectionname: ${{ variables.serviceConnectionName_test_mngdapp }}
      tf_stateresourcegroupname: ${{ variables.tfStateResourceGroupName_test_mngdapp }}
      tf_statestorageaccountname: ${{ variables.tfStateStorageAccountName_test_mngdapp }}
      tf_statecontainername: ${{ variables.tfStateContainerName_test_mngdapp }}
      tf_statefile: ${{ variables.tfStateFile_test_mngdapp }}
      env_configuration: ${{ variables.envConfiguration_test_mngdapp }}
      enable_stage: ${{ variables.enable_test_mngdapp }}
      agent_pool: ${{ variables.agent_pool_test_mngdapp }}
      enable_apply: ${{ variables.enable_apply_test_mngdapp }}
  # mngddtgw Dev
  - template: ../../../Common/azure-deployment.yml
    parameters:
      environment_name: "Testmngddtgw"
      branch_name: ${{ variables.branch_name }}
      tf_workingfolder: ${{ variables.tfWorkingFolder_mngddtgw }}
      stage_name: "Test_mngddtgw"
      deployment_jobname: "Deployment_Test_mngddtgw"
      teardown_jobname: "Teardown_Test_mngddtgw"
      teardown_environment: ${{ variables.teardownEnvironment_test_mngddtgw }}
      service_connectionname: ${{ variables.serviceConnectionName_test_mngddtgw }}
      tf_stateresourcegroupname: ${{ variables.tfStateResourceGroupName_test_mngddtgw }}
      tf_statestorageaccountname: ${{ variables.tfStateStorageAccountName_test_mngddtgw }}
      tf_statecontainername: ${{ variables.tfStateContainerName_test_mngddtgw }}
      tf_statefile: ${{ variables.tfStateFile_test_mngddtgw }}
      env_configuration: ${{ variables.envConfiguration_test_mngddtgw }}
      enable_stage: ${{ variables.enable_test_mngddtgw }}
      agent_pool: ${{ variables.agent_pool_test_mngddtgw }}
      enable_apply: ${{ variables.enable_apply_test_mngddtgw }}
  # Mngdapp Production
  - template: ../../../Common/azure-deployment.yml
    parameters:
      environment_name: "Productionmngdapp"
      branch_name: ${{ variables.branch_name }}
      tf_workingfolder: ${{ variables.tfWorkingFolder_mngdapp }}
      stage_name: "Production_mngdapp"
      deployment_jobname: "Deployment_Production_mngdapp"
      teardown_jobname: "Teardown_Production_mngdapp"
      teardown_environment: ${{ variables.teardownEnvironment_production_mngdapp }}
      service_connectionname: ${{ variables.serviceConnectionName_production_mngdapp }}
      tf_stateresourcegroupname: ${{ variables.tfStateResourceGroupName_production_mngdapp }}
      tf_statestorageaccountname: ${{ variables.tfStateStorageAccountName_production_mngdapp }}
      tf_statecontainername: ${{ variables.tfStateContainerName_production_mngdapp }}
      tf_statefile: ${{ variables.tfStateFile_production_mngdapp }}
      env_configuration: ${{ variables.envConfiguration_production_mngdapp }}
      enable_stage: ${{ variables.enable_production_mngdapp }}
      agent_pool: ${{ variables.agent_pool_production_mngdapp }}
      enable_apply: ${{ variables.enable_apply_production_mngdapp }}
  # MngdHS Production
  - template: ../../../Common/azure-deployment.yml
    parameters:
      environment_name: "Production_EIT_mngd"
      branch_name: ${{ variables.branch_name }}
      tf_workingfolder: ${{ variables.tfWorkingFolder_mngd }}
      stage_name: "Production_EIT_mngd"
      deployment_jobname: "Deployment_Production_mngd"
      teardown_jobname: "Teardown_Production_mngd"
      teardown_environment: ${{ variables.teardownEnvironment_production_mngd }}
      service_connectionname: ${{ variables.serviceConnectionName_production_mngd }}
      tf_stateresourcegroupname: ${{ variables.tfStateResourceGroupName_production_mngd }}
      tf_statestorageaccountname: ${{ variables.tfStateStorageAccountName_production_mngd }}
      tf_statecontainername: ${{ variables.tfStateContainerName_production_mngd }}
      tf_statefile: ${{ variables.tfStateFile_production_mngd }}
      env_configuration: ${{ variables.envConfiguration_production_mngd }}
      enable_stage: ${{ variables.enable_production_mngd }}
      agent_pool: ${{ variables.agent_pool_production_mngd }}
      enable_apply: ${{ variables.enable_apply_production_mngd }}

  # MngdHS nonProduction
  - template: ../../../Common/azure-deployment.yml
    parameters:
      environment_name: "nonProduction_EIT_mngd"
      branch_name: ${{ variables.branch_name }}
      tf_workingfolder: ${{ variables.tfWorkingFolder_mngd }}
      stage_name: "nonProduction_EIT_mngd"
      deployment_jobname: "Deployment_nonProduction_mngd"
      teardown_jobname: "Teardown_nonProduction_mngd"
      teardown_environment: ${{ variables.teardownEnvironment_nonproduction_mngd }}
      service_connectionname: ${{ variables.serviceConnectionName_nonproduction_mngd }}
      tf_stateresourcegroupname: ${{ variables.tfStateResourceGroupName_nonproduction_mngd }}
      tf_statestorageaccountname: ${{ variables.tfStateStorageAccountName_nonproduction_mngd }}
      tf_statecontainername: ${{ variables.tfStateContainerName_nonproduction_mngd }}
      tf_statefile: ${{ variables.tfStateFile_nonproduction_mngd }}
      env_configuration: ${{ variables.envConfiguration_nonproduction_mngd }}
      enable_stage: ${{ variables.enable_nonproduction_mngd }}
      agent_pool: ${{ variables.agent_pool_nonproduction_mngd }}
      enable_apply: ${{ variables.enable_apply_nonproduction_mngd }}
