---
trigger: none
variables:
 - group: createkeyvaultsecrets
 - template: variables.yml
pool:
   name: "Ubuntu-Agents"
steps:
- task: AzurePowerShell@5
  displayName: 'Azure PowerShell script: FilePath'
  inputs:
    azureSubscription: ${{ variables.azureSubscription}} #'az-lz-staging'
    ScriptPath: '20_pipelines/HighSecure/17_azure-kv-secrets/azure-kv-secrets.ps1'
    ScriptArguments: '-storageAccount $(storageAccount_name) -storageAccountKey $(mdwhs-aux-sa-key) -shareName $(file_shareName) -sourcefile $(sourcefile) -kvname $(kvname)'
    azurePowerShellVersion: LatestVersion
