---
trigger:
  branches:
    include:
      - production-hs
  paths:
    include:
      - /10_projects/13_GenCoreHS/10_Paas
      - /20_pipelines/HighSecure/10_Paas/58_gencore
      - /env/10_Paas/58_gencore
# pr:
#   branches:
#     include:
#       - production-hs
#   paths:
#     include:
#       - /10_projects/13_GenCoreHS/10_Paas
#       - /20_pipelines/HighSecure/10_Paas/58_gencore
#       - /env/10_Paas/58_gencore

variables:
  - template: 01_gencore-Deployment.yml
  - template: 02_gencore-paas-vars-production.yml
  - template: 03_gencore-paas-vars-nonprod.yml
  - template: /20_pipelines/HighSecure/github-branch.yml

# Anything below should not be modified ##
stages:
# Gencore Non-Prod ##
  - template: ../../../Common/azure-deployment.yml
    parameters:
      environment_name: "nonprod_gencore"
      branch_name: ${{ variables.branch_name }}
      tf_workingfolder: ${{ variables.tfWorkingFolder_nonprod_gencore }}
      stage_name: "nonprod_gencore"
      deployment_jobname: "Deployment_nonprod_gencore"
      teardown_jobname: "Teardown_nonprod_gencore"
      teardown_environment: ${{ variables.teardownEnvironment_nonprod_gencore }}
      service_connectionname: ${{ variables.serviceConnectionName_nonprod_gencore }}
      tf_stateresourcegroupname: ${{ variables.tfStateResourceGroupName_nonprod_gencore }}
      tf_statestorageaccountname: ${{ variables.tfStateStorageAccountName_nonprod_gencore }}
      tf_statecontainername: ${{ variables.tfStateContainerName_nonprod_gencore }}
      tf_statefile: ${{ variables.tfStateFile_nonprod_gencore }}
      env_configuration: ${{ variables.envConfiguration_nonprod_gencore }}
      enable_stage: ${{ variables.enable_nonprod_gencore }}
      agent_pool: ${{ variables.agent_pool_nonprod_gencore }}
      enable_apply: ${{ variables.enable_apply_nonprod_gencore }}
  # Gencore Production
  - template: ../../../Common/azure-deployment.yml
    parameters:
      environment_name: "Production_gencore"
      branch_name: ${{ variables.branch_name }}
      tf_workingfolder: ${{ variables.tfWorkingFolder_gencore }}
      stage_name: "Productiongencore"
      deployment_jobname: "Deployment_Production_gencore"
      teardown_jobname: "Teardown_Production_gencore"
      teardown_environment: ${{ variables.teardownEnvironment_production_gencore }}
      service_connectionname: ${{ variables.serviceConnectionName_production_gencore }}
      tf_stateresourcegroupname: ${{ variables.tfStateResourceGroupName_production_gencore }}
      tf_statestorageaccountname: ${{ variables.tfStateStorageAccountName_production_gencore }}
      tf_statecontainername: ${{ variables.tfStateContainerName_production_gencore }}
      tf_statefile: ${{ variables.tfStateFile_production_gencore }}
      env_configuration: ${{ variables.envConfiguration_production_gencore }}
      enable_stage: ${{ variables.enable_production_gencore }}
      agent_pool: ${{ variables.agent_pool_production_gencore }}
      enable_apply: ${{ variables.enable_apply_production_gencore }}
