location    = "eu-west-2"
vpc_name    = ["prod_vpc", "nonprod_vpc", "vpc_hub"]
az          = ["eu-west-2a", "eu-west-2b", "eu-west-2c"]
cidr_block  = ["172.16.0.0/16", "172.16.0.0/24", "172.16.0.0/18"]
env         = ["prod", "nonprod", "vpchub"]
igw_name    = ["prod_igw", "nonprod_igw"]
rt          = "vpchub_rt"
eni_name    = ["prodsubnet1_eni", "prodsubnet2_eni", "prodsubnet3_eni", "preprodsubnet1_eni", "preprodsubnet2_eni", "preprodsubnet3_eni", "testsubnet1_eni", "testsubnet2_eni", "testsubnet3_eni"]
nacl_name   = ["prodsubnet1_nacl", "prodsubnet2_nacl", "prodsubnet3_nacl", "preprodsubnet1_nacl", "preprodsubnet2_nacl", "preprodsubnet3_nacl", "testsubnet1_nacl", "testsubnet2_nacl", "testsubnet3_nacl"]
subnet_name = ["prod_subnet1", "prod_subnet2", "prod_subnet3", "preprod_subnet1", "preprod_subnet2", "preprod_subnet3", "test_subnet1", "test_subnet2", "test_subnet3", "vpchub_subnet"]