---
repos:
  - repo: git@github.com:edfenergy/eit-devops-pre-commit-generic.git
    rev: 0.1.3
    hooks:
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: remove-crlf
      - id: auto_generate_changelog
  - repo: git@github.com:edfenergy/eit-devops-pre-commit-terraform.git
    rev: 0.1.0
    hooks:
      - id: terraform_fmt
        exclude: Common/
      - id: terraform_docs
        exclude: Common/
      - id: terraform_tflint
        exclude: Common/
      - id: terraform_validate
        exclude: Common/
      - id: checkov
        exclude: Common/
