---
trigger:
  branches:
    include:
      - production-hs
  paths:
    include:
      - /10_projects/09_M365HS/10_Paas
      - /20_pipelines/HighSecure/10_Paas/55_m365
      - /env/10_Paas/55_m365
# pr:
#   branches:
#     include:
#       - production-hs
#   paths:
#     include:
#       - /10_projects/07_CenAudit/17_Keyvault
#       - /20_pipelines/HighSecure/17_Keyvault/54_m365
#       - /env/17_Keyvault/54_m365

# pool:
#   name: "Ubuntu-Agents"

variables:
  - template: 01_m365-Deployment.yml
  - template: 02_m365-paas-vars-production.yml
  - template: /20_pipelines/HighSecure/github-branch.yml

# Anything below should not be modified ##

stages:
# Production m365HS
  - template: ../../../Common/azure-deployment.yml
    parameters:
      environment_name: "Productionm365HS"
      branch_name: ${{ variables.branch_name }}
      tf_workingfolder: ${{ variables.tfWorkingFolder_m365 }}
      stage_name: "Production_m365HS"
      deployment_jobname: "Deployment_Production_m365App"
      teardown_jobname: "Teardown_Production_m365App"
      teardown_environment: ${{ variables.teardownEnvironment_production_m365 }}
      service_connectionname: ${{ variables.serviceConnectionName_production_m365 }}
      tf_stateresourcegroupname: ${{ variables.tfStateResourceGroupName_production_m365 }}
      tf_statestorageaccountname: ${{ variables.tfStateStorageAccountName_production_m365 }}
      tf_statecontainername: ${{ variables.tfStateContainerName_production_m365 }}
      tf_statefile: ${{ variables.tfStateFile_production_m365 }}
      env_configuration: ${{ variables.envConfiguration_production_m365 }}
      enable_stage: ${{ variables.enable_production_m365 }}
      agent_pool: ${{ variables.agent_pool_production_m365 }}
      enable_apply: ${{ variables.enable_apply_production_m365 }}
