environment               = "Sandpit"
updateManagmentRgName     = "eit-uks-prd-ss-m365-rg"
updateManagmentRgLocation = "UK South"
laWorkspacename           = "eit-uks-alz-ss-loga-01"
laWorkspaceSku            = "Free"
automationAccountName     = "eit-uks-prd-m365-aa-01"
automationAccountSku      = "Basic"
# lawSolutionName           = "Updates"
