---
variables:
  # control-m production
  enable_production_controlm: false
  teardownEnvironment_production_controlm: false

  #control-m non-prod
  enable_nonprod_controlm: false
  teardownEnvironment_nonprod_controlm: false

  #control-m sandpit
  enable_sandpit_controlm: false
  teardownEnvironment_sandpit_controlm: false

  # deployment info
  deployment_reason: "regular"
  deployment_id: "dev-work-20210208-b"
