---
trigger:
  branches:
    include:
      - production-hs
  paths:
    include:
      - /10_projects/03_EamApp/07_Policies
      - /20_pipelines/HighSecure/07_Policies/50_eam
      - /env/07_Policies/50_eam
# pr:
#   branches:
#     include:
#       - production-hs
#   paths:
#     include:
#       - /10_projects/03_EamApp/07_Policies
#       - /20_pipelines/HighSecure/07_Policies/50_eam
#       - /env/07_Policies/50_eam

#test comment-Z
# pool:
#   name: "Ubuntu-Agents"

variables:
  - template: 01_eam-Deployment.yml
  - template: 02_eam-policies-vars-production.yml
  - template: /20_pipelines/HighSecure/github-branch.yml

# Anything below should not be modified ##
stages:
# Eam Production
  - template: ../../../Common/azure-deployment.yml
    parameters:
      environment_name: "ProductionEam"
      branch_name: ${{ variables.branch_name }}
      tf_workingfolder: ${{ variables.tfWorkingFolder_eamapp }}
      stage_name: "Production_EamApp"
      deployment_jobname: "Deployment_Production_EamApp"
      teardown_jobname: "Teardown_Production_EamApp"
      teardown_environment: ${{ variables.teardownEnvironment_production_eamapp }}
      service_connectionname: ${{ variables.serviceConnectionName_production_eamapp }}
      tf_stateresourcegroupname: ${{ variables.tfStateResourceGroupName_production_eamapp }}
      tf_statestorageaccountname: ${{ variables.tfStateStorageAccountName_production_eamapp }}
      tf_statecontainername: ${{ variables.tfStateContainerName_production_eamapp }}
      tf_statefile: ${{ variables.tfStateFile_production_eamapp }}
      env_configuration: ${{ variables.envConfiguration_production_eamapp }}
      enable_stage: ${{ variables.enable_production_eamapp }}
      agent_pool: ${{ variables.agent_pool_production_eamapp }}
      enable_apply: ${{ variables.enable_apply_production_eamapp }}
