---
trigger:
  branches:
    include:
      - production-hs
  paths:
    include:
      - /10_projects/05_DataStrategy/01_Networking_prd
      - /10_projects/05_DataStrategy/01_Networking_tst
      - /20_pipelines/HighSecure/01_Networking/52_data
      - /env/01_Networking/52_data
# pr:
#   branches:
#     include:
#       - production-hs
#   paths:
#     include:
#       - /10_projects/05_DataStrategy/01_Networking
#       - /20_pipelines/HighSecure/01_Networking/52_data
#       - /env/01_Networking/52_data

# pool:
#   name: "Ubuntu-Agents"

variables:
  - template: 01_data-Deployment.yml
  - template: 02_data-networking-vars-production.yml
  - template: 03_data-networking-vars-test.yml
  - template: /20_pipelines/HighSecure/github-branch.yml

# Anything below should not be modified ##
stages:
  # test MDW
  - template: ../../../Common/azure-deployment.yml
    parameters:
      environment_name: "Testdataapp"
      branch_name: ${{ variables.branch_name }}
      tf_workingfolder: ${{ variables.tfWorkingFolder_tst_dataapp }}
      stage_name: "Test_dataapp"
      deployment_jobname: "Deployment_Test_dataapp"
      teardown_jobname: "Teardown_Test_dataapp"
      teardown_environment: ${{ variables.teardownEnvironment_test_dataapp }}
      service_connectionname: ${{ variables.serviceConnectionName_test_dataapp }}
      tf_stateresourcegroupname: ${{ variables.tfStateResourceGroupName_test_dataapp }}
      tf_statestorageaccountname: ${{ variables.tfStateStorageAccountName_test_dataapp }}
      tf_statecontainername: ${{ variables.tfStateContainerName_test_dataapp }}
      tf_statefile: ${{ variables.tfStateFile_test_dataapp }}
      env_configuration: ${{ variables.envConfiguration_test_dataapp }}
      enable_stage: ${{ variables.enable_test_dataapp }}
      agent_pool: ${{ variables.agent_pool_test_dataapp }}
      enable_apply: ${{ variables.enable_apply_test_dataapp }}
  # Production MDW
  - template: ../../../Common/azure-deployment.yml
    parameters:
      environment_name: "Productiondataapp"
      branch_name: ${{ variables.branch_name }}
      tf_workingfolder: ${{ variables.tfWorkingFolder_prd_dataapp }}
      stage_name: "Production_dataapp"
      deployment_jobname: "Deployment_Production_dataapp"
      teardown_jobname: "Teardown_Production_dataapp"
      teardown_environment: ${{ variables.teardownEnvironment_production_dataapp }}
      service_connectionname: ${{ variables.serviceConnectionName_production_dataapp }}
      tf_stateresourcegroupname: ${{ variables.tfStateResourceGroupName_production_dataapp }}
      tf_statestorageaccountname: ${{ variables.tfStateStorageAccountName_production_dataapp }}
      tf_statecontainername: ${{ variables.tfStateContainerName_production_dataapp }}
      tf_statefile: ${{ variables.tfStateFile_production_dataapp }}
      env_configuration: ${{ variables.envConfiguration_production_dataapp }}
      enable_stage: ${{ variables.enable_production_dataapp }}
      agent_pool: ${{ variables.agent_pool_production_dataapp }}
      enable_apply: ${{ variables.enable_apply_production_dataapp }}
