# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:

trigger:
- main

pool: 'Ubuntu-Agents'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build and test your project.
    echo Add tasks to deploy your project.
  displayName: 'Run a multi-line script'
